//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlthietbi_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int DeviceID { get; set; }
        public string DeviceName { get; set; }
        public int TypeID { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<System.DateTime> WarrantyUntil { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
    
        public virtual DeviceType DeviceType { get; set; }
    }
}
