//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlthietbi_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginHistory
    {
        public int AccountID { get; set; }
        public System.DateTime LoginTime { get; set; }
        public int LoginID { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> LogoutTime { get; set; }
    }
}
